[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Build command to create dist folder
  command = "npm run build"

# Force Netlify to use this configuration
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  # Serve assets directly (don't redirect to index.html)
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  # Serve service worker directly
  from = "/sw.js"
  to = "/sw.js"
  status = 200

[[redirects]]
  # Handle client-side routing for everything else
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # PWA headers
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  # JavaScript files headers
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript"

[[headers]]
  # CSS files headers
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "text/css"

[[headers]]
  # Images headers
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Images headers
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Images headers
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"