[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Build command to create dist folder
  command = "npm run build"

# Force Netlify to use this configuration
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  # Serve assets directly (don't redirect to index.html)
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Service Worker redirects REMOVIDOS - causaba problemas de cache

[[redirects]]
  # Handle client-side routing for everything else
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# PWA Service Worker headers REMOVIDOS - causaba problemas de cache

[[headers]]
  # JavaScript files headers - Cache disabled for development
  for = "*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  # CSS files headers - Cache disabled for development  
  for = "*.css"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  # Images headers
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Images headers
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Images headers
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"